name: Update NFL Standings

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours during season
  workflow_dispatch:

jobs:
  update-standings:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create directories
      run: |
        mkdir -p docs archive
        
    - name: Update standings
      run: |
        python src/data-processors/team-stats.py
      continue-on-error: true
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/ archive/
        git diff --staged --quiet || git commit -m "Update NFL standings - $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}